[platform]
soc = "nrf52"
boards = ["nk3am"]
target = "thumbv7em-none-eabihf"

[parameters]
flash_origin = 0x00001000
filesystem_boundary = 0xD8000
filesystem_end = 0xEC000

[identifier]
usb_id_vendor = 0x20A0
usb_id_product = 0x42B2
usb_manufacturer = "Nitrokey"
usb_product = "Nitrokey 3"
ccid_issuer = "Nitrokey"
