[package]
name = "usb-classes"
version = "0.1.0"
edition = "2021"

[dependencies]
apdu-dispatch.workspace = true
ctaphid-dispatch.workspace = true
delog.workspace = true
embedded-time.workspace = true
ref-swap = "0.1.0"
trussed-core.workspace = true
usb-device.workspace = true
usbd-ccid.workspace = true
usbd-ctaphid.workspace = true

[features]
default = []

# 512-byte CCID bulk endpoints, as required when enumerating at high speed.
highspeed-usb = ["usbd-ccid/highspeed-usb"]

log-all = []
log-none = []
log-trace = []
log-debug = []
log-info = []
log-warn = []
log-error = []
