[factory-settings]
# debug-access = "Disabled"
rot-fingerprint = "e48f84151d42861f654cd7bc9111d0b12ca7974a0139e4217a278819cb473cf9"

[factory-settings.usb-id]
vid = 0x20a0
pid = 0x42dd

[factory-settings.secure-boot-configuration]
puf-keycode-generation-disabled = true
dice-computation-disabled = true
secure-boot-enabled = true
use-rsa4096-keys = true
