FROM fedora:latest
# RUN dnf update
RUN dnf install -y python3 git curl llvm clang glibc-devel.i686 clang-devel gcc-arm-linux-gnu
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rust.sh && bash rust.sh -y
RUN echo "source $HOME/.cargo/env" > ~/.bashrc
RUN $HOME/.cargo/bin/cargo install flip-link
RUN $HOME/.cargo/bin/rustup target add thumbv8m.main-none-eabi
RUN $HOME/.cargo/bin/cargo install cargo-binutils
RUN $HOME/.cargo/bin/rustup component add llvm-tools-preview
RUN dnf -y install wget python
ENV PATH="$HOME/.cargo/bin/:${PATH}"
