[package]
name = "nfc-device"
version = "0.0.1"
authors = ["Conor Patrick <conor@solokeys.com>"]
edition = "2018"

[dependencies]
delog.workspace = true
embedded-time.workspace = true
heapless = "0.9"
nb = "1"

apdu-dispatch.workspace = true
iso7816 = "0.2"
interchange.workspace = true

[features]
default = []

log-all = []
log-none = []
log-trace = []
log-debug = []
log-info = []
log-warn = []
log-error = []
