
# cargo-vet audits file

[[wildcard-audits.apdu-app]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/apdu-dispatch"
start = "2026-03-25"
end = "2027-06-17"

[[wildcard-audits.apdu-dispatch]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/apdu-dispatch"
start = "2026-03-25"
end = "2027-06-17"

[[wildcard-audits.ctap-types]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/ctap-types"
start = "2026-03-25"
end = "2027-06-17"

[[wildcard-audits.ctaphid-app]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/ctaphid-dispatch"
start = "2026-03-23"
end = "2027-06-17"

[[wildcard-audits.ctaphid-dispatch]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/ctaphid-dispatch"
start = "2026-03-23"
end = "2027-06-17"

[[wildcard-audits.fido-authenticator]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/fido-authenticator"
start = "2025-09-02"
end = "2027-06-17"

[[wildcard-audits.heapless-bytes]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/heapless-bytes"
start = "2025-09-18"
end = "2027-06-17"

[[wildcard-audits.iso7816]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/iso7816"
start = "2025-09-25"
end = "2027-06-17"

[[wildcard-audits.littlefs2]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/littlefs2"
start = "2026-03-09"
end = "2027-06-17"

[[wildcard-audits.littlefs2-core]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/littlefs2"
start = "2025-10-16"
end = "2027-06-17"

[[wildcard-audits.littlefs2-sys]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/littlefs2-sys"
start = "2026-03-03"
end = "2027-06-17"

[[wildcard-audits.lpc55-hal]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:lpc55/lpc55-hal"
start = "2026-03-20"
end = "2027-06-17"

[[wildcard-audits.se05x]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:Nitrokey/se05x"
start = "2025-09-25"
end = "2027-06-17"

[[wildcard-audits.trussed-auth]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/trussed-auth"
start = "2026-03-25"
end = "2027-06-17"

[[wildcard-audits.trussed-chunked]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/trussed-staging"
start = "2026-03-23"
end = "2027-06-17"

[[wildcard-audits.trussed-core]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/trussed"
start = "2026-03-20"
end = "2027-06-17"

[[wildcard-audits.trussed-fs-info]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/trussed-staging"
start = "2026-03-23"
end = "2027-06-17"

[[wildcard-audits.trussed-hkdf]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/trussed-staging"
start = "2026-03-23"
end = "2027-06-17"

[[wildcard-audits.trussed-hpke]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/trussed-staging"
start = "2026-03-23"
end = "2027-06-17"

[[wildcard-audits.trussed-manage]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/trussed-staging"
start = "2026-03-23"
end = "2027-06-17"

[[wildcard-audits.trussed-rsa-types]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/trussed-rsa-backend"
start = "2026-03-25"
end = "2027-06-17"

[[wildcard-audits.trussed-se050-manage]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:Nitrokey/trussed-se050-backend"
start = "2026-03-25"
end = "2027-06-17"

[[wildcard-audits.trussed-wrap-key-to-file]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/trussed-staging"
start = "2026-03-23"
end = "2027-06-17"

[[wildcard-audits.usbd-ccid]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/usbd-ccid"
start = "2026-03-25"
end = "2027-06-17"

[[wildcard-audits.usbd-ctaphid]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
trusted-publisher = "github:trussed-dev/usbd-ctaphid"
start = "2026-03-25"
end = "2027-06-17"

[[audits.cbor-smol]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
version = "0.5.1"

[[audits.clap_lex]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
delta = "0.7.4 -> 0.7.5"

[[audits.cosey]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
version = "0.4.0"

[[audits.crunchy]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
delta = "0.2.3 -> 0.2.4"

[[audits.delog]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
version = "0.1.8"

[[audits.flexiber]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
version = "0.2.0"

[[audits.flexiber_derive]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
version = "0.1.3"

[[audits.inout]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
delta = "0.1.3 -> 0.1.4"

[[audits.interchange]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
version = "0.3.2"

[[audits.log]]
who = "Sosthène Guédon <sosthene@nitrokey.com>"
criteria = "safe-to-deploy"
delta = "0.4.29 -> 0.4.32"
notes = "Mostly lint/formatting changes, other changes are sensible"

[[audits.memchr]]
who = "Sosthène Guédon <sosthene@nitrokey.com>"
criteria = "safe-to-deploy"
delta = "2.7.5 -> 2.8.2"
notes = "Mostly changes that correspond to applying lints, otherwise addition of one vector operation that is as safe as the existing ones"

[[audits.num]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
delta = "0.4.0 -> 0.3.1"

[[audits.potential_utf]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
delta = "0.1.2 -> 0.1.3"

[[audits.regex]]
who = "Sosthène Guédon <sosthene@nitrokey.com>"
criteria = "safe-to-deploy"
delta = "1.12.3 -> 1.12.4"
notes = "No changes in this crate, changes are only in dependencies but their version criterias are not changed"

[[audits.regex]]
who = "Sosthène Guédon <sosthene@nitrokey.com>"
criteria = "safe-to-run"
delta = "1.12.3 -> 1.12.4"
notes = "Nothing has been changed in the code of this crate, only in the dependencies that are part of the regex project"

[[audits.regex-syntax]]
who = "Sosthène Guédon <sosthene@nitrokey.com>"
criteria = "safe-to-deploy"
delta = "0.8.5 -> 0.8.11"
notes = "Mostly lint/formatting changes small feature change"

[[audits.serde-indexed]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
version = "0.1.1"

[[audits.serde_spanned]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
delta = "1.0.3 -> 1.0.2"

[[audits.serial_test]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
delta = "2.0.0 -> 1.0.0"

[[audits.shlex]]
who = "Sosthène Guédon <sosthene@nitrokey.com>"
criteria = "safe-to-deploy"
delta = "1.3.0 -> 2.0.1"
notes = "Mostly function removals"

[[audits.stable_deref_trait]]
who = "Sosthène Guédon <sosthene@nitrokey.com>"
criteria = "safe-to-deploy"
delta = "1.2.0 -> 1.2.1"
notes = "Just a stricter CFG and support for `Cow`"

[[audits.toml_writer]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
delta = "1.0.6+spec-1.1.0 -> 1.0.3"

[[audits.trussed]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
version = "0.2.0-rc.1"

[[audits.trussed-auth-backend]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
version = "0.2.0-rc.1"

[[audits.trussed-rsa-alloc]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
version = "0.2.0-rc.1"

[[audits.trussed-se050-backend]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
version = "0.8.0-rc.1"

[[audits.trussed-staging]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
version = "0.5.0-rc.1"

[[audits.trussed-usbip]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
version = "0.1.0-rc.1"

[[audits.version_check]]
who = "Sosthène Guédon <sosthene@nitrokey.com>"
criteria = "safe-to-deploy"
delta = "0.9.4 -> 0.9.5"
notes = "Only documentation changes"

[[audits.winapi-util]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
delta = "0.1.9 -> 0.1.11"

[[audits.windows-link]]
who = "Robin Krahl <robin@nitrokey.com>"
criteria = "safe-to-deploy"
delta = "0.1.1 -> 0.1.3"
