MEMORY
{
  /* NOTE K = KiBi = 1024 bytes */
  FLASH : ORIGIN = ##FLASH_BASE##, LENGTH = ##FLASH_LENGTH##
  FILESYSTEM : ORIGIN = ##FS_BASE##, LENGTH = ##FS_LENGTH##
  RAM : ORIGIN = 0x20000000, LENGTH = 256K
}
