name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Install Rust toolchain
        run: rustup show active-toolchain || rustup toolchain install
      - name: Check components
        run: make check-components
      - name: Check usbip runner
        run: |
          cd runners/usbip
          cargo check
          cargo check --features provisioner
          cargo check --features test

  check-thumbv7em:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Install Rust toolchain
        run: rustup show active-toolchain || rustup toolchain install
      - name: Install build dependencies
        run: sudo apt-get install gcc-arm-none-eabi
      - name: Check embedded runner
        run: |
          cd runners/embedded
          make check-nk3am.bl
          make check-nk3am.bl FEATURES=provisioner
          make check-nk3am.bl FEATURES=develop,log-all
          make check-nk3am.bl FEATURES=develop,log-all,provisioner
      - name: Check nkpk runner
        run: |
          cd runners/nkpk
          cargo check
          cargo check --features provisioner
          cargo check --features develop,log-all
          cargo check --features develop,log-all,provisioner

  check-thumbv8m:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Install Rust toolchain
        run: rustup show active-toolchain || rustup toolchain install
      - name: Install build dependencies
        run: sudo apt-get install gcc-arm-none-eabi
      - name: Check embedded runner
        run: |
          cd runners/embedded
          make check-nk3xn
          make check-nk3xn FEATURES=provisioner
          make check-nk3xn FEATURES=develop,log-all
          make check-nk3xn FEATURES=develop,log-all,provisioner

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Install Rust toolchain
        run: rustup show active-toolchain || rustup toolchain install
      - name: Install build dependencies
        run: sudo apt-get install gcc-arm-none-eabi
      - name: Lint
        run: make lint
        env:
          RUSTFLAGS: "-Dwarnings"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Install Rust toolchain
        run: rustup show active-toolchain || rustup toolchain install
      - name: Run software tests
        run: make software-tests
