[parameters]
flash_origin = 0x00000000
filesystem_boundary = 0x93000
filesystem_end = 0x9D800

[identifier]
usb_id_vendor = 0x20A0
usb_id_product = 0x42EF
usb_manufacturer = "Nitrokey"
usb_product = "Nitrokey 3"
ccid_issuer = "Nitrokey"
